var usahtml5map_map_cfg_0 = {
  mapWidth: 0,
  zoomEnable: false,
  zoomOnlyOnMobile: false,
  zoomEnableControls: true,
  zoomIgnoreMouseScroll: false,
  zoomMax: 2,
  zoomStep: 0.2,
  pointColor: "#FFC480",
  pointColorOver: "#DC8135",
  pointNameColor: "#000",
  pointNameColorOver: "#222",
  pointNameStrokeColor: "#FFFFFF",
  pointNameStrokeColorOver: "#FFFFFF",
  pointNameFontSize: "12pxpx",
  pointNameFontWeight: "bold",
  pointNameStroke: true,
  pointBorderWidth: 0.5,
  pointBorderColor: "#ffffff",
  pointBorderColorOver: "#eeeeee",
  shadowAllow: false,
  shadowWidth: 1.5,
  shadowOpacity: 0.2,
  shadowColor: "black",
  shadowX: 0,
  shadowY: 0,
  iPhoneLink: true,
  isNewWindow: false,
  borderWidth: "1.01",
  borderColor: "#e9eaea",
  borderColorOver: "#ffffff",
  nameColor: "#ffffff",
  nameColorOver: "#ffffff",
  popupNameColor: "#000",
  nameFontSize: "10px",
  popupNameFontSize: "20px",
  nameFontWeight: "bold",
  overDelay: 300,
  nameStroke: false,
  nameStrokeColor: "#000000",
  nameStrokeColorOver: "#000000",
  freezeTooltipOnClick: false,
  tooltipOnHighlightIn: true,
  tooltipOnMobileCentralize: true,
  tooltipOnMobileWidth: "80%",
  tooltipOnMobileVPosition: "bottom",
  map_data: {
    st1: {
      id: 1,
      name: "Alabama",
      shortname: "AL",
      link: "https://www.cceionline.com/alabama/",
      comment: "",
      image: "",
      color_map: "#7798BA",
      color_map_over: "#366CA3",
      isNewWindow: 0,
    },
    st2: {
      id: 2,
      name: "Alaska",
      shortname: "AK ",
      link: "https://www.cceionline.com/alaska/",
      comment: "",
      image: "",
      color_map: "#7798BA",
      color_map_over: "#366CA3",
      isNewWindow: 0,
    },
    st3: {
      id: 3,
      name: "Arizona",
      shortname: "AZ ",
      link: "https://www.cceionline.com/arizona/",
      comment: "",
      image: "",
      color_map: "#7798BA",
      color_map_over: "#366CA3",
      isNewWindow: 0,
    },
    st4: {
      id: 4,
      name: "Arkansas",
      shortname: "AR",
      link: "https://www.cceionline.com/arkansas/",
      comment: "",
      image: "",
      color_map: "#7798BA",
      color_map_over: "#366CA3",
      isNewWindow: 0,
    },
    st5: {
      id: 5,
      name: "California",
      shortname: "CA",
      link: "https://www.cceionline.com/california/",
      comment: "",
      image: "",
      color_map: "#7798BA",
      color_map_over: "#366CA3",
      isNewWindow: 0,
    },
    st6: {
      id: 6,
      name: "Colorado",
      shortname: "CO",
      link: "https://www.cceionline.com/colorado/",
      comment: "",
      image: "",
      color_map: "#7798BA",
      color_map_over: "#366CA3",
      isNewWindow: 0,
    },
    st7: {
      id: 7,
      name: "Connecticut",
      shortname: "CT",
      link: "https://www.cceionline.com/connecticut/",
      comment: "",
      image: "",
      color_map: "#7798BA",
      color_map_over: "#366CA3",
      isNewWindow: 0,
    },
    st8: {
      id: 8,
      name: "Delaware",
      shortname: "DE",
      link: "https://www.cceionline.com/delaware/",
      comment: "",
      image: "",
      color_map: "#7798BA",
      color_map_over: "#366CA3",
      isNewWindow: 0,
    },
    st9: {
      id: 9,
      name: "District of Columbia",
      shortname: "DC",
      link: "https://www.cceionline.com/washington-dc/",
      comment: "",
      image: "",
      color_map: "#7798BA",
      color_map_over: "#366CA3",
      isNewWindow: 0,
    },
    st10: {
      id: 10,
      name: "Florida",
      shortname: "FL",
      link: "https://www.cceionline.com/florida/",
      comment: "",
      image: "",
      color_map: "#7798BA",
      color_map_over: "#366CA3",
      isNewWindow: 0,
    },
    st11: {
      id: 11,
      name: "Georgia",
      shortname: "GA",
      link: "https://www.cceionline.com/georgia/",
      comment: "",
      image: "",
      color_map: "#7798BA",
      color_map_over: "#366CA3",
      isNewWindow: 0,
    },
    st12: {
      id: 12,
      name: "Hawaii",
      shortname: "HI",
      link: "https://www.cceionline.com/hawaii/",
      comment: "",
      image: "",
      color_map: "#7798BA",
      color_map_over: "#366CA3",
      isNewWindow: 0,
    },
    st13: {
      id: 13,
      name: "Idaho",
      shortname: "ID",
      link: "https://www.cceionline.com/idaho/",
      comment: "",
      image: "",
      color_map: "#7798BA",
      color_map_over: "#366CA3",
      isNewWindow: 0,
    },
    st14: {
      id: 14,
      name: "Illinois",
      shortname: "IL",
      link: "https://www.cceionline.com/illinois/",
      comment: "",
      image: "",
      color_map: "#7798BA",
      color_map_over: "#366CA3",
      isNewWindow: 0,
    },
    st15: {
      id: 15,
      name: "Indiana",
      shortname: "IN",
      link: "https://www.cceionline.com/indiana/",
      comment: "",
      image: "",
      color_map: "#7798BA",
      color_map_over: "#366CA3",
      isNewWindow: 0,
    },
    st16: {
      id: 16,
      name: "Iowa",
      shortname: "IA",
      link: "https://www.cceionline.com/iowa/",
      comment: "",
      image: "",
      color_map: "#7798BA",
      color_map_over: "#366CA3",
      isNewWindow: 0,
    },
    st17: {
      id: 17,
      name: "Kansas",
      shortname: "KS",
      link: "https://www.cceionline.com/kansas/",
      comment: "",
      image: "",
      color_map: "#7798BA",
      color_map_over: "#366CA3",
      isNewWindow: 0,
    },
    st18: {
      id: 18,
      name: "Kentucky",
      shortname: "KY",
      link: "https://www.cceionline.com/kentucky/",
      comment: "",
      image: "",
      color_map: "#7798BA",
      color_map_over: "#366CA3",
      isNewWindow: 0,
    },
    st19: {
      id: 19,
      name: "Louisiana",
      shortname: "LA",
      link: "https://www.cceionline.com/louisiana/",
      comment: "",
      image: "",
      color_map: "#7798BA",
      color_map_over: "#366CA3",
      isNewWindow: 0,
    },
    st20: {
      id: 20,
      name: "Maine",
      shortname: "ME",
      link: "https://www.cceionline.com/maine/",
      comment: "",
      image: "",
      color_map: "#7798BA",
      color_map_over: "#366CA3",
      isNewWindow: 0,
    },
    st21: {
      id: 21,
      name: "Maryland",
      shortname: "MD",
      link: "https://www.cceionline.com/maryland/",
      comment: "",
      image: "",
      color_map: "#7798BA",
      color_map_over: "#366CA3",
      isNewWindow: 0,
    },
    st22: {
      id: 22,
      name: "Massachusetts",
      shortname: "MA",
      link: "https://www.cceionline.com/massachusetts/",
      comment: "",
      image: "",
      color_map: "#7798BA",
      color_map_over: "#366CA3",
      isNewWindow: 0,
    },
    st23: {
      id: 23,
      name: "Michigan",
      shortname: "MI",
      link: "https://www.cceionline.com/michigan/",
      comment: "",
      image: "",
      color_map: "#7798BA",
      color_map_over: "#366CA3",
      isNewWindow: 0,
    },
    st24: {
      id: 24,
      name: "Minnesota",
      shortname: "MN",
      link: "https://www.cceionline.com/minnesota/",
      comment: "",
      image: "",
      color_map: "#7798BA",
      color_map_over: "#366CA3",
      isNewWindow: 0,
    },
    st25: {
      id: 25,
      name: "Mississippi",
      shortname: "MS",
      link: "https://www.cceionline.com/mississippi/",
      comment: "",
      image: "",
      color_map: "#7798BA",
      color_map_over: "#366CA3",
      isNewWindow: 0,
    },
    st26: {
      id: 26,
      name: "Missouri",
      shortname: "MO",
      link: "https://www.cceionline.com/missouri/",
      comment: "",
      image: "",
      color_map: "#7798BA",
      color_map_over: "#366CA3",
      isNewWindow: 0,
    },
    st27: {
      id: 27,
      name: "Montana",
      shortname: "MT",
      link: "https://www.cceionline.com/montana/",
      comment: "",
      image: "",
      color_map: "#7798BA",
      color_map_over: "#366CA3",
      isNewWindow: 0,
    },
    st28: {
      id: 28,
      name: "Nebraska",
      shortname: "NE",
      link: "https://www.cceionline.com/nebraska/",
      comment: "",
      image: "",
      color_map: "#7798BA",
      color_map_over: "#366CA3",
      isNewWindow: 0,
    },
    st29: {
      id: 29,
      name: "Nevada",
      shortname: "NV",
      link: "https://www.cceionline.com/nevada/",
      comment: "",
      image: "",
      color_map: "#7798BA",
      color_map_over: "#366CA3",
      isNewWindow: 0,
    },
    st30: {
      id: 30,
      name: "New Hampshire",
      shortname: "NH",
      link: "https://www.cceionline.com/new-hampshire/",
      comment: "",
      image: "",
      color_map: "#7798BA",
      color_map_over: "#366CA3",
      isNewWindow: 0,
    },
    st31: {
      id: 31,
      name: "New Jersey",
      shortname: "NJ",
      link: "https://www.cceionline.com/new-jersey/",
      comment: "",
      image: "",
      color_map: "#7798BA",
      color_map_over: "#366CA3",
      isNewWindow: 0,
    },
    st32: {
      id: 32,
      name: "New Mexico",
      shortname: "NM",
      link: "https://www.cceionline.com/new-mexico/",
      comment: "",
      image: "",
      color_map: "#7798BA",
      color_map_over: "#366CA3",
      isNewWindow: 0,
    },
    st33: {
      id: 33,
      name: "New York",
      shortname: "NY",
      link: "https://www.cceionline.com/new-york/",
      comment: "",
      image: "",
      color_map: "#7798BA",
      color_map_over: "#366CA3",
      isNewWindow: 0,
    },
    st34: {
      id: 34,
      name: "North Carolina",
      shortname: "NC",
      link: "https://www.cceionline.com/north-carolina/",
      comment: "",
      image: "",
      color_map: "#7798BA",
      color_map_over: "#366CA3",
      isNewWindow: 0,
    },
    st35: {
      id: 35,
      name: "North Dakota",
      shortname: "ND",
      link: "https://www.cceionline.com/north-dakota/",
      comment: "",
      image: "",
      color_map: "#7798BA",
      color_map_over: "#366CA3",
      isNewWindow: 0,
    },
    st36: {
      id: 36,
      name: "Ohio",
      shortname: "OH",
      link: "https://www.cceionline.com/ohio/",
      comment: "",
      image: "",
      color_map: "#7798BA",
      color_map_over: "#366CA3",
      isNewWindow: 0,
    },
    st37: {
      id: 37,
      name: "Oklahoma",
      shortname: "OK",
      link: "https://www.cceionline.com/oklahoma/",
      comment: "",
      image: "",
      color_map: "#7798BA",
      color_map_over: "#366CA3",
      isNewWindow: 0,
    },
    st38: {
      id: 38,
      name: "Oregon",
      shortname: "OR",
      link: "https://www.cceionline.com/oregon/",
      comment: "",
      image: "",
      color_map: "#7798BA",
      color_map_over: "#366CA3",
      isNewWindow: 0,
    },
    st39: {
      id: 39,
      name: "Pennsylvania",
      shortname: "PA",
      link: "https://www.cceionline.com/pennsylvania/",
      comment: "",
      image: "",
      color_map: "#7798BA",
      color_map_over: "#366CA3",
      isNewWindow: 0,
    },
    st40: {
      id: 40,
      name: "Rhode Island",
      shortname: "RI",
      link: "https://www.cceionline.com/rhode-island/",
      comment: "",
      image: "",
      color_map: "#7798BA",
      color_map_over: "#366CA3",
      isNewWindow: 0,
    },
    st41: {
      id: 41,
      name: "South Carolina",
      shortname: "SC",
      link: "https://www.cceionline.com/south-carolina/",
      comment: "",
      image: "",
      color_map: "#7798BA",
      color_map_over: "#366CA3",
      isNewWindow: 0,
    },
    st42: {
      id: 42,
      name: "South Dakota",
      shortname: "SD",
      link: "https://www.cceionline.com/south-dakota/",
      comment: "",
      image: "",
      color_map: "#7798BA",
      color_map_over: "#366CA3",
      isNewWindow: 0,
    },
    st43: {
      id: 43,
      name: "Tennessee",
      shortname: "TN",
      link: "https://www.cceionline.com/tennessee/",
      comment: "",
      image: "",
      color_map: "#7798BA",
      color_map_over: "#366CA3",
      isNewWindow: 0,
    },
    st44: {
      id: 44,
      name: "Texas",
      shortname: "TX",
      link: "https://www.cceionline.com/texas/",
      comment: "",
      image: "",
      color_map: "#7798BA",
      color_map_over: "#366CA3",
      isNewWindow: 0,
    },
    st45: {
      id: 45,
      name: "Utah",
      shortname: "UT",
      link: "https://www.cceionline.com/utah/",
      comment: "",
      image: "",
      color_map: "#7798BA",
      color_map_over: "#366CA3",
      isNewWindow: 0,
    },
    st46: {
      id: 46,
      name: "Vermont",
      shortname: "VT",
      link: "https://www.cceionline.com/vermont/",
      comment: "",
      image: "",
      color_map: "#7798BA",
      color_map_over: "#366CA3",
      isNewWindow: 0,
    },
    st47: {
      id: 47,
      name: "Virginia",
      shortname: "VA",
      link: "https://www.cceionline.com/virginia/",
      comment: "",
      image: "",
      color_map: "#7798BA",
      color_map_over: "#366CA3",
      isNewWindow: 0,
    },
    st48: {
      id: 48,
      name: "Washington",
      shortname: "WA",
      link: "https://www.cceionline.com/washington/",
      comment: "",
      image: "",
      color_map: "#7798BA",
      color_map_over: "#366CA3",
      isNewWindow: 0,
    },
    st49: {
      id: 49,
      name: "West Virginia",
      shortname: "WV",
      link: "https://www.cceionline.com/west-virginia/",
      comment: "",
      image: "",
      color_map: "#7798BA",
      color_map_over: "#366CA3",
      isNewWindow: 0,
    },
    st50: {
      id: 50,
      name: "Wisconsin",
      shortname: "WI",
      link: "https://www.cceionline.com/wisconsin/",
      comment: "",
      image: "",
      color_map: "#7798BA",
      color_map_over: "#366CA3",
      isNewWindow: 0,
    },
    st51: {
      id: 51,
      name: "Wyoming",
      shortname: "WY",
      link: "https://www.cceionline.com/wyoming/",
      comment: "",
      image: "",
      color_map: "#7798BA",
      color_map_over: "#366CA3",
      isNewWindow: 0,
    },
  },
  groups: {},
  points: {},
};
